name: "Hugo and Firebase"
description: "Builds the Hugo site and deploys to Firebase Hosting."
branding:
  icon: "code"
  color: "gray-dark"
inputs:
    firebaseToken:
      description: "Firebase token (see README for support)."
      required: false
    firebaseServiceAccount:
      description: "Firebase service account JSON."
      required: false
    projectId:
      description: "The project to deploy to."
      required: false
    hugoParams:
      description: "Build params for the hugo command."
      required: false
      default: "-D"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.firebaseToken }}
    - ${{ inputs.firebaseServiceAccount }}
    - ${{ inputs.projectId }}
    - ${{ inputs.hugoParams }}