name: "Hugo and Firebase"
description: "Builds the Hugo site and deploys to Firebase Hosting."
branding:
  icon: "code"
  color: "gray-dark"
inputs:
    firebase-token:
      description: "Firebase token (see README for support)."
      required: true
    hugo-params:
      description: "Build params for the hugo command."
      required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.firebase-token }}
    - ${{ inputs.alias }}
    - ${{ inputs.hugo-params }}